#!/usr/bin/env bash
#
# Neofetch config file
# https://github.com/dylanaraps/neofetch

print_info() {
    info title
    info underline

    info "OS" distro
    info "KL" kernel
    info "UP" uptime
    info "PK" packages
    info "SH" shell
    info "WM" wm
    info "TR" term
    info "CPU" cpu
    info "GPU" gpu
    info "Mem" memory
    info "Disk" disk
    info "Font" font

    info line_break
    info cols
    info line_break
}

kernel_shorthand="on"
distro_shorthand="off"
os_arch="off"
uptime_shorthand="on"
shell_path="on"
shell_version="off"
speed_type="bios_limit"
speed_shorthand="on"
cpu_shorthand="tiny"
cpu_speed="off"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
gpu_type="all"
refresh_rate="off"
gtk_shorthand="on"
gtk2="on"
gtk3="off"
public_ip_host="http://ident.me"
disk_show=('/')
disk_subtitle="mount"
song_shorthand="off"
install_time="off"
install_time_format="12h"
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="ー"
block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="ascii"
image_source="arch"
ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="fit"
crop_offset="center"
image_size="256px"
gap=3
yoffset=1
xoffset=1
background_color=
scrot="off"
scrot_cmd="auto"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="teknik"
config_version="3.2.0"
