#!/bin/bash

sxhkd &
nitrogen --restore &
compton --config ~/.config/compton/config -b
xsetroot -cursor_name left_ptr
polybar watch &
setxkbmap dvorak &
greenclip daemon &

bspc monitor -d     

bspc config active_border_color \#752a2a
bspc config focused_border_color \#752a2a
bspc config normal_border_color \#752a2a
 
bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap           12

bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord border=off
bspc rule -a Termite border=off
bspc rule -a FirefoxNightly border=off
